### ISSUE TITLE
Documentation Generators / platform possibilities

### ISSUE THREAD

**Issue by joeyklee** [ml5js/ml5-website-2#3]
Hi! 

Maybe we can start a list of possibilities for doc generators/platforms for building the website w/ some templating help:

I've started using docsify and seems way more friendly than Docusauraus (which is what the website is currently made from).

See: https://docsify.js.org/#/

**Comment by cvalenzuela** [comment]
Agree! We have been using docsify for https://docs.runwayapp.ai/ and it has been great so far

**Comment by MimiOnuoha** [comment]
Jumping in here late to just say that docsify looks great!

**Comment by joeyklee** [comment]
As we're currently using our own homebrewed solution using gatsby.js, closing this issue now :)
